CREATE DATABASE EVERYMIND;
USE EVERYMIND;
CREATE TABLE produtos(
`id` INT PRIMARY KEY AUTO_INCREMENT,
 `nome` VARCHAR(255) NOT NULL,
 `codigo` VARCHAR(255) NOT NULL,
 `descricao` VARCHAR(500),
 `preco` DATE NOT NULL,
 PRIMARY KEY(`id`));